### ISSUE TITLE
where conditions are not escaped

### ISSUE THREAD

**Issue by mren** [snd/mesa#15]
As the attributes in insert and update are escaped via `mohair.escape` I expected the `where` conditions to be escaped, too. 

```javascript
model.where({someColumn: true}); // doesn't escape
model.where({'"someColumn"': true}); // manual escaping is tedious
```

As a hotfix I used this method

```javascript
model.where(escape({someColumn: true}));
function escape(where) {
  if (Array.isArray(where)) {
    return where.map(escape);
  }
  return _.object(_.map(where, function(value, key) {
    var isSpecialKey = key[0] === '$';
    var quotedKey = isSpecialKey ? key : '"' + key + '"';
    return [quotedKey, isDictionary(value) ? escape(value) : value];
  }));

  function isDictionary(object) {
    return _.isObject(object) && !_.isFunction(object);
  }
}
```

Which currently works for normal keys, special keys (`$or`, ...), but not yet for raw sql (`where('foo && ?', foo)`)

Would be handsome if this would be baked into mesa or configurable.

Do you have any opinions or preferences?

**Comment by snd** [comment]
definitely fixed in 1.0.0-alpha.11
