### ISSUE TITLE
Minor usability glitch with chained promises

### ISSUE THREAD

**Issue by mren** [snd/mesa#16]
This is a minor usability glitch I discovered while working with the api.
I shot myself several times with this error. It occurred one time to often and therefore I will report it.

Instead of `model.find().then(postProcess)` I did `model.find(postProcess)` which will swallow the `postProcess` function and return something unexpected. As there will be no error it can get hard to detect the source of the problem

I would have 2 proposals to avoid this situation

a) assert to have no arguments for all functions without parameters (`find`, `first`, `update`, `delete`)
b) treat `find(postProcess)` as `find().then(postProcess)`

Do you think this is an glitch which should be fixed? And if yes do you have a preference on how to solve this?

**Comment by snd** [comment]
fixed in 108ebb40cf40eabbdc0624d248057fbf357f764b
